title: Sally's Bakes
description: Vegan cakes, pies, pastries and sweets in Bury, Prestwich, Whitefield, Radcliffe and nearby
baseurl: ""
url: "https://sallysbakesbury.co.uk"

email_address: sallysbakes@outlook.com
facebook_page: SallysBakes
phone_number: 07940 576822
address: Bury, Greater Manchester, UK

env: production

markdown: kramdown
plugins:
  - jekyll-sitemap

collections:
  posts:
    output: true
    permalink: /:collection/:path
  pages:
    output: true
    permalink: /:path
  ingredients:
    output: true
    permalink: /menu/:path

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "ingredients"
    values:
      layout: "ingredient"
  - scope:
      path: "google0000000000000.html"
    values:
      sitemap: false

sass:
  sass_dir: _sass

exclude:
  - Gemfile
  - LICENSE
  - default.nix
  - gemset.nix
  - package-lock.json
  - shell.nix
  - "*.md"
